// breaking to turn off temporarily

# site heavily inspired by https://pfrazee.github.io

# Blog settings
permalink: /blog/:title
show_drafts: true

# My variables
title: Marc Shapiro
name: Marc Shapiro
description: Engineer, data systems

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-redirect-from
